### ISSUE TITLE
Support liquid >= 4.0.0

### ISSUE THREAD

**Issue by ohadschn** [gemfarmer/jekyll-liquify#1]
The current `liquid` version limitation of `[">= 2.5", "< 4.0"]` does not include the [latest stable `liquid` release](https://rubygems.org/gems/liquid/versions/4.0.0). Worse, the [latest stable `jekyll` release](https://rubygems.org/gems/jekyll/versions/3.5.2) can't be used as it depends on `liquid ~> 4.0`.

**Comment by gemfarmer** [comment]
oi! Changed in the latest commit, https://github.com/gemfarmer/jekyll-liquify/commit/92b6b5b114fb13a5ef1e6fea8d71aaa7731ee551. Sorry for the delay!  

Let me know if you have any issues with the latest version. :)
